services:
  ros:
    build:
      context: .
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
    devices:
      - /dev/video0
    volumes:
      - ~/DSD_theGreeter/ros_ws:/ros_ws
