services:
  ros:
    container_name: thegreeter
    build:
      context: .
      args:
        - USER_NAME=$USER
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
    environment:
      - DISPLAY=$DISPLAY
    devices:
      - /dev/video0
    volumes:
      - ~/DSD_theGreeter/ros_ws:/ros_ws/:rw
      - /tmp/.X11-unix/:/tmp/.X11-unix/:rw
    stdin_open: true
    tty: true
